[package]
name = "fs_watcher"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["io-util", "macros", "process", "rt", "rt-multi-thread", "signal", "sync"] }
tokio-stream = "0.1.18"
